

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
    - name: Pull Docker image
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker pull ghcr.io/tecosys/rental:latest
    - name: Delete Old docker container
      run: sudo docker rm -f rental-container || true
    - name: Run Docker Container
      run: sudo docker run -d --name rental-container -p 8005:8005 ghcr.io/tecosys/rental:latest
